<!--HTML SNIPPET GENERATED BY GIMP

WARNING!! This is NOT a fully valid HTML document, it is rather a piece of
HTML generated by GIMP's py-slice plugin that should be embedded in an HTML
or XHTML document to be valid.

Replace the href targets in the anchor (<a >) for your URLS to have it working
as a menu.
 -->
<table cellpadding="0" border="0" cellspacing="0">
  <tr>
    <td><img alt=" " src="{{ asset ('/assets/template/pluit/slice_0_0.png') }}" style="width: 117px;  height: 67px; border-width: 0px;"></td>
    <td><img alt=" " src="{{ asset ('/assets/template/pluit/slice_0_1.png') }}" style="width: 43px;  height: 67px; border-width: 0px;"></td>
    <td><img alt=" " src="{{ asset ('/assets/template/pluit/slice_0_2.png') }}" style="width: 128px;  height: 67px; border-width: 0px;"></td>
</tr>

  <tr>
    <td><img alt=" " src="{{ asset ('/assets/template/pluit/slice_1_0.png') }}" style="width: 117px;  height: 41px; border-width: 0px;"></td>
    <td><a onclick="Desk(9)" class="tmbl" id="tombolkursi_9"><img id="imgdesk9" src="{{ asset ('/assets/template/pluit/tombol9.png') }}" class="available" style="width: 43px; height: 41px; border-width: 0px;"></a></td>
    <td><img alt=" " src="{{ asset ('/assets/template/pluit/slice_1_2.png') }}" style="width: 128px;  height: 41px; border-width: 0px;"></td>
</tr>

  <tr>
    <td><img alt=" " src="{{ asset ('/assets/template/pluit/slice_2_0.png') }}" style="width: 117px;  height: 54px; border-width: 0px;"></td>
    <td><a href="#"><img alt=" " src="{{ asset ('/assets/template/pluit/slice_2_1.png') }}"  style="width: 43px; height: 54px; border-width: 0px;"></a></td>
    <td><img alt=" " src="{{ asset ('/assets/template/pluit/slice_2_2.png') }}" style="width: 128px;  height: 54px; border-width: 0px;"></td>
</tr>

  <tr>
    <td><img alt=" " src="{{ asset ('/assets/template/pluit/slice_3_0.png') }}" style="width: 117px;  height: 41px; border-width: 0px;"></td>
    <td><a onclick="Desk(10)" class="tmbl" id="tombolkursi_10"><img id="imgdesk10" src="{{ asset ('/assets/template/pluit/tombol10.png') }}" class="available" style="width: 43px; height: 41px; border-width: 0px;"></a></td>
    <td><img alt=" " src="{{ asset ('/assets/template/pluit/slice_3_2.png') }}" style="width: 128px;  height: 41px; border-width: 0px;"></td>
</tr>

  <tr>
    <td><img alt=" " src="{{ asset ('/assets/template/pluit/slice_4_0.png') }}" style="width: 117px;  height: 53px; border-width: 0px;"></td>
    <td><a href="#"><img alt=" " src="{{ asset ('/assets/template/pluit/slice_4_1.png') }}"  style="width: 43px; height: 53px; border-width: 0px;"></a></td>
    <td><img alt=" " src="{{ asset ('/assets/template/pluit/slice_4_2.png') }}" style="width: 128px;  height: 53px; border-width: 0px;"></td>
</tr>

  <tr>
    <td><img alt=" " src="{{ asset ('/assets/template/pluit/slice_5_0.png') }}" style="width: 117px;  height: 42px; border-width: 0px;"></td>
    <td><a onclick="Desk(11)" class="tmbl" id="tombolkursi_11"><img id="imgdesk11" src="{{ asset ('/assets/template/pluit/tombol11.png') }}" class="available" style="width: 43px; height: 42px; border-width: 0px;"></a></td>
    <td><img alt=" " src="{{ asset ('/assets/template/pluit/slice_5_2.png') }}" style="width: 128px;  height: 42px; border-width: 0px;"></td>
</tr>

  <tr>
    <td><img alt=" " src="{{ asset ('/assets/template/pluit/slice_6_0.png') }}" style="width: 117px;  height: 58px; border-width: 0px;"></td>
    <td><a href="#"><img alt=" " src="{{ asset ('/assets/template/pluit/slice_6_1.png') }}"  style="width: 43px; height: 58px; border-width: 0px;"></a></td>
    <td><img alt=" " src="{{ asset ('/assets/template/pluit/slice_6_2.png') }}" style="width: 128px;  height: 58px; border-width: 0px;"></td>
</tr>

  <tr>
    <td><img alt=" " src="{{ asset ('/assets/template/pluit/slice_7_0.png') }}" style="width: 117px;  height: 42px; border-width: 0px;"></td>
    <td><a onclick="Desk(12)" class="tmbl" id="tombolkursi_12"><img id="imgdesk12" src="{{ asset ('/assets/template/pluit/tombol12.png') }}" class="available" style="width: 43px; height: 42px; border-width: 0px;"></a></td>
    <td><img alt=" " src="{{ asset ('/assets/template/pluit/slice_7_2.png') }}" style="width: 128px;  height: 42px; border-width: 0px;"></td>
</tr>

  <tr>
    <td><img alt=" " src="{{ asset ('/assets/template/pluit/slice_8_0.png') }}" style="width: 117px;  height: 64px; border-width: 0px;"></td>
    <td><img alt=" " src="{{ asset ('/assets/template/pluit/slice_8_1.png') }}" style="width: 43px;  height: 64px; border-width: 0px;"></td>
    <td><img alt=" " src="{{ asset ('/assets/template/pluit/slice_8_2.png') }}" style="width: 128px;  height: 64px; border-width: 0px;"></td>
</tr>

</table>

<script type="text/javascript">
  
function Desk(id){

  var tanggal = $('#tanggal').val();
  var type = $('#type').val();
  var dari = $('#dari').val();
  var sampai = $('#sampai').val();

  if(type == 'hour'){
      if(tanggal == '' || dari == '' || sampai == ''){
          swal({
              title: "Perhatikan",
              text: "Harap isi Tanggal atau Waktu dulu!",
              icon: "error",
              buttons: false,
              timer: 2000,
          });
      } else {
          $('.available').attr("src", "../assets/template/pluit/tombol9.png");
          $('#imgdesk'+id).attr("src", "../assets/template/pluit/tombol"+id+"_p.png");

          $.ajax({
            type: 'POST',
            url: "{{ route('workingspace.pilih') }}",
            data: {
                '_token': $('input[name=_token]').val(),
                'id': id,
            },
            success: function(data) {

              $('#pilihdesk').html(data.desk_code);
              $('#valuedesk').val(data.id);
              $('#namadesk').val(data.desk_code);

            }

          });
      }


  } else {

      if(tanggal == ''){
          swal({
              title: "Perhatikan",
              text: "Harap isi Tanggal terlebih dahulu!",
              icon: "error",
              buttons: false,
              timer: 2000,
          });
      } else {
          $('.available').attr("src", "../assets/template/pluit/tombol9.png");
          $('#imgdesk'+id).attr("src", "../assets/template/pluit/tombol"+id+"_p.png");

          $.ajax({
            type: 'POST',
            url: "{{ route('workingspace.pilih') }}",
            data: {
                '_token': $('input[name=_token]').val(),
                'id': id,
            },
            success: function(data) {

              $('#pilihdesk').html(data.desk_code);
              $('#valuedesk').val(data.id);
              $('#namadesk').val(data.desk_code);
            }

          });
      }

  }

  
}

</script>

